### PR TITLE
feat: add flag to control restart of capella

### PR DESCRIPTION
**Pull request by jamilraichouni**
the default value for the introduced env var
RESTART_CAPELLA is 1.

### CODE REVIEW

**Comment by MoritzWeber0** [comment]
Could you add a section in the `README`, which describes the new environment variable and the corresponding behaviour?

**Comment by jamilraichouni** [comment]
> Could you add a section in the `README`, which describes the new environment variable and the corresponding behaviour?

Done, have a look at https://github.com/DSD-DBS/capella-dockerimages/pull/41/commits/e0575bae59de39b0e8f60bbdef29dd1b1528d459

**Review by MoritzWeber0 — APPROVED** [review]
LGTM

**Comment by MoritzWeber0** [comment]
I moved the environment variables description to the `docker run` section as the variables are set during runtime and not during build. Can you look over it quickly? @jamilraichouni

**Review by jamilraichouni — COMMENTED** [review]
yes, this makes sense. missed that.

**Pull request merged**
